movie_api/movie/urls.py
''' Importing Views '''
from . import views
from django.urls import path

app_name = 'movie'

urlpatterns = [
    path('', views.index, name='index'),
    path('search', views.search, name='search_results'),
    path('movie/<str:movie_name>/', views.getmovie, name='movie_desc'),
]

movie_api/movie_api/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('', include('movie.urls',namespace='movie')),
    path('admin/', admin.site.urls),
]

movie_api/movie/models.py
from django.db import models

# Create your models here.

movie_api/movie/views.py
from django.shortcuts import render
import requests
from movie_api.settings import API_KEY

# Create your views here.

def index(request):
    sender = {'index':True}
    return render(request, 'movie/main.html', sender)

def search(request):
    m = request.GET.get('q')
    url = 'http://www.omdbapi.com/?apikey='+ API_KEY
    params = {'s': m}
    r = requests.get(url, params=params)
    movie = r.json()
    if 'Error' in movie:
        sender = {'Error': True, 'search': m}
    else:
        sender = {'Error': False,'movie': movie,'search':m}
    return render(request, 'movie/main.html', sender)

def getmovie(request, movie_name):
    url = 'http://www.omdbapi.com/?apikey='+ API_KEY
    params = {'t':movie_name}
    r = requests.get(url, params=params)
    movie = r.json()

    if 'Error' in movie:
        sender = {'Error': True, 'search': movie_name}
    else:
        first = ['Title','Year','Actors','Runtime','Genre','Director']
        try:
            ratings = movie['Ratings']
        except Exception:
            ratings = []
        second = ['Plot','Language', 'Country', 'Released', 'BoxOffice', 'Production',  'Writer','Response',
         'Rated', 'DVD','Type', 'imdbID','imdbVotes', 'imdbRating', 'Metascore', 'Awards', 'Website']
        sender = {'movie': movie,'first':first,'second':second,'ratings':ratings}
    return render(request, 'movie/movie.html', sender)

movie_api/movie/templates/movie/base.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>{% block title %}Title{% endblock %}</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">{% load static %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<link href="https://fonts.googleapis.com/css?family='Merriweather'&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Playfair+Display&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<link href="https://fonts.googleapis.com/css?family=Noto+Serif|Playfair+Display&display=swap" rel="stylesheet">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<link href="{% static 'css/main.css' %}" rel="stylesheet" type="text/css">
</head>
<body>
<nav class="navbar navbar-expand-sm bg-dark navbar-dark mn">
	
  <form class="form-inline form-in-new" action="{% url 'movie:search_results' %}" style="margin-left: auto;
    margin-right: auto; ">
    <input class="form-control mr-sm-2 in" type="text" name='q' value="{{search}}" placeholder="Movie Search"  required>
   <center><button class="btn btn-succem/css?family='Merriweather';&s bt" type="submit">Search</button></center> 
  </form>
</nav>
<br>
{% block body %}
{% endblock %}
<br>
</body>
</html!important>

movie_api/movie/templates/movie/main.html
{% extends 'movie/base.html' %}
{% block title %}Movie Search{% endblock %}
{% block body %}
    {% load static %}
<div class="container">
{% if index %}
<center>
  <p>
  <span class="glyphicon" style="font-size: 25px;">&#xe093;</span>
  </p>
</center>
<br> 
<center><h2>Search Any Movie From Movie Search</h2></center>
{% else %}
  <center><h3 style="font-family: 'Merriweather';">Search Result for : {{search}}</h3></center>
  <br>
 <table class="table" style="border:1px solid rgba(0,0,0,0.16);background-color: white; ">
    <thead>
      <tr>
        <th style="padding:13px; ">IMDB ID</th>
        <th style="padding:13px; ">Movie Title</th>
        <th style="padding:13px; ">Year</th>
        <th style="padding:13px; ">Poster</th>
      </tr>
    </thead>
    <tbody>
    {% if not Error %}
        {% for name in movie|get_item:'Search'%}
        <tr style="border: 2px;font-family: 'Merriweather'!important;">
          <td style="padding: 13px;text-transform: uppercase">{{name|get_item:'imdbID'}}</td>
         
          <td style="padding: 13px;"><a href="{% url 'movie:movie_desc' name|get_item:'Title' %}" >{{name|get_item:'Title'}}</a></td>
          <td style="padding: 13px;">{{name|get_item:'Year'}}</td>
          <td style="padding: 13px;"><img src="{{name|get_item:'Poster'}}" style="width: 100px;height: 120px;"></td>
          </tr>
        {% endfor %}
    {% else %}
    <div class="alert alert-danger">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <center><strong>{{search}} </strong>is not a valid movie name&nbsp;<strong>!</strong></center> 
    </div>
    {% endif %}    
  </tbody>
  </table
  >
{% endif %}
</div>
{% endblock %}

movie_api/movie/templates/movie/movie.html
{% extends 'movie/base.html' %}
{% block title %}Movie View{% endblock %}
{% block body %}
    {% load static %}
 <div class="container" style="box-shadow:0 0px 1px 0 rgba(0,0,0,0.16), 0 0px 5px 0 rgba(0,0,0,0.12);padding: 10px;background-color: white;border-radius: 10px;">
 	<div class="row">
    	<div class="col-sm-12" style="font-size: 25px;padding: 7px;font-family:'Playfair';"><center>Movie Description</center></div>
    </div>
 </div>  
 
  <div class="container" style="box-shadow:0 1px 2px 0 rgba(0,0,0,0.16), 0 1px 2px 0 rgba(0,0,0,0.12);padding: 45px;background-color: white;margin-top:10px; border-radius: 10px;">
    <!-- Control the column width, and how they should appear on different devices -->
      <div class="row">
  {% if not Error %}
      <div class="col-sm-3 mob" style="position: relative;min-height: 250px;
  z-index: 1;padding: 10px;"><img src="{{ movie|get_item:'Poster' }}" style="position: absolute;top: 0;left: 0;height: 100%;width: 100%;z-index: -1;"></div>
       
      <div class="col-sm-9">
		{% for name in first %}  
		<div class="row row-adj">
      		<div class="col-sm-3 title">{{name}}</div>
      		<div class="col-sm-9 title-value">{{movie|get_item:name}}</div>
		  </div>
		{% endfor %}
      </div>
      <br>
      <br>
      <div class="col-sm-12" >
      	<br>
		  {% for name in second %}
		  <div class="row row-adj">
      		<div class="col-sm-3 title">{{name}}</div>
      		<div class="col-sm-9 title-value">{{movie|get_item:name}}</div>
		  </div>
		  {% endfor %}
      </div>


    </div>
    <br>
    
    <div class="row">
      <div class="col-sm-12"> 
      	<table class="table table-bordered ts">
    <thead>
      <tr>
        <th>Rating</th>
        <th>Company</th>
   
      </tr>
    </thead>
    <tbody>
		{% for name in ratings %}
      <tr>
       {% for n,m in name.items %}
        <td>{{m}}</td>
        {% endfor %}
	  </tr>
	  {% endfor %}
    </tbody>
  </table>
</div>
</div>
  {% else %}
    <div class="alert alert-danger" style="width: 100%;">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <center><strong>{{search}} </strong>is not a valid movie name&nbsp;<strong>!</strong></center> 
    </div>
  {% endif %}   
</div>
</div>
{% endblock %}